apiVersion: apps/v1
kind: Deployment
metadata:
  name: suika
spec:
  selector:
    matchLabels:
      app: suika
  replicas: 1
  template:
    metadata:
      labels:
        app: suika
    spec:
      containers:
      - name: suika
        image: okteto.dev/suika:latest
        ports:
        - containerPort: 9050
        
---
    
apiVersion: v1
kind: Service
metadata:
  name: suika
spec:
  type: LoadBalancer 
  ports:
    - name: https
      port: 9050
  selector:
    app: suika
